name: Node.js CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.13
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13'
      - name: Install dependencies
      - run: yarn install --frozen-lockfile
      - run: yarn format:check
      - run: yarn build --if-present